import type { Metadata } from "next";
import { Inter } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MobileRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative flex h-full min-h-screen w-full items-center justify-center bg-muted">
      <div className="absolute  top-0 mx-auto h-[840px] w-[400px] max-w-screen-sm bg-[url('/images/ip_15_frame.png')] bg-contain bg-no-repeat p-5"></div>
      <div className="relative h-[840px] w-[400px] max-w-screen-sm overflow-hidden bg-white">
        {children}
      </div>
    </div>
  );
}
