import type { Metadata } from "next";
import { Inter } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MobileRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full h-full min-h-screen bg-muted flex justify-center items-center">
      <div className="max-w-screen-sm w-[400px] h-[840px] bg-white overflow-hidden">{children}</div>
    </div>
  );
}
