import { Home, ListOrdered, ShoppingCart, UserRound } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Mobile App Prototype",
  description: "Generated by create next app",
};

export default function MobilenavLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-full w-full">
      {children}
      <nav className="sticky bottom-0 w-full border-t">
        <ul className="flex w-full justify-around">
          <li>
            <Link href="/mobile/nav/home" className="p-3 block">
              <Home />
              <span className="sr-only">Beranda</span>
            </Link>
          </li>
          <li>
            <Link href="/mobile/nav/home" className="p-3 block">
              <ListOrdered />
              <span className="sr-only">Peringkat</span>
            </Link>
          </li>
          <li>
            <Link href="/mobile/nav/home" className="p-3 block">
              <ShoppingCart />
              <span className="sr-only">Toko</span>
            </Link>
          </li>
          <li>
            <Link href="/mobile/nav/home" className="p-3 block">
              <UserRound />
              <span className="sr-only">Profile</span>
            </Link>
          </li>
        </ul>
      </nav>
    </div>
  );
}
