import type { Metadata } from "next";
import Link from "next/link";

import { Home, ListOrdered, ShoppingCart, UserRound } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

export const metadata: Metadata = {
  title: "Mobile App Prototype",
  description: "Generated by create next app",
};

export default function MobilenavLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-full w-full flex-col">
      <header className="relative z-50 flex w-full flex-col">
        <div className="flex h-6 w-full items-center justify-center bg-black">
          <p className="text-xs text-gray-500">tidak ada jaringan</p>
        </div>
        <div className="flex items-center justify-between border-b p-2 pr-3">
          <h1 className="text-lg font-bold">Mobile App</h1>

          <div>
            <Link href="/mobile/nav/credit">
              <Avatar className="h-8 w-8">
                <AvatarImage src="https://safebooru.org//samples/4619/sample_5429d7b3d4bec2e681972180df2e673af1f39c65.jpg?4834439" />
                <AvatarFallback>user avatar</AvatarFallback>
              </Avatar>
            </Link>
          </div>
        </div>
      </header>

      <main className="flex h-full w-full flex-1 items-center justify-center">
        {children}
      </main>

      <nav className="sticky bottom-0 z-50 w-full border-t bg-white">
        <ul className="flex w-full justify-around">
          <li>
            <Link href="/mobile/nav/home" className="block p-3">
              <Home />
              <span className="sr-only">Beranda</span>
            </Link>
          </li>
          <li>
            <Link href="/mobile/nav/rank" className="block p-3">
              <ListOrdered />
              <span className="sr-only">Peringkat</span>
            </Link>
          </li>
          <li>
            <Link href="/mobile/nav/shop" className="block p-3">
              <ShoppingCart />
              <span className="sr-only">Toko</span>
            </Link>
          </li>
          <li>
            <Link href="/mobile/nav/profile" className="block p-3">
              <UserRound />
              <span className="sr-only">Profile</span>
            </Link>
          </li>
        </ul>
      </nav>
    </div>
  );
}
